version: '3.9'

services:
  tomcat:
    build: ./tomcat
    ports:
      - "8081:8080"
    container_name: tomcat-server
    depends_on:
      - db

  db:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
