
version: '3.9'

services:
  tomcat:
    build: ./tomcat
    ports:
      - "8080:8080"
    container_name: tomcat-server
    depends_on:
      - db
  db:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}

    volumes:
      - ./mysql/data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password



